### PR TITLE
fix: first IP of CIDR range

### PR DESCRIPTION
**Pull request by alfiyansys**
image

fix first IP from CIDR notation input.

CIDR 192.168.25.0/21 : 
Correct CIDR range: 192.168.24.0 ~ 192.168.31.255

image

### CODE REVIEW

**Comment by fadhilyori** [comment]
The `firstIP` variable specifies the lower IP address within the range for the package. 
What are your thoughts on this?

**Comment by alfiyansys** [comment]
CIDR / subnet range should be constant wichever condition is, which is /21 accounts for 2048 hosts.
therefore first IP should be first IP from designated within specified CIDR range (/21), not based on their IP inputs (192.168.25.0). 
If the inputs on the middle of so called 'subnets' (192.168.25.0/21), it should be treated as an single IP address, not IP address range, therefore it puts /21 (subnet) lower priority than single IP address, it should be higher priority to parse. 
If CIDR notation is specified, and treated them as subnet, we need to convert specified IP into their respective network ID, 192.168.24.0/21, so we have full 2048 hosts.

**Comment by fadhilyori** [comment]
Okay, thank you for your input. I agree with you. 

I believe the `firstIP` parameter is no longer needed since we can obtain it from `firstIp.Mask(cidr.Mask)`. Could you please remove the `firstIp` parameter from both the `GenerateIPListFromCIDR` function and the `GenerateIPListFromCIDRString` function?

**Comment by alfiyansys** [comment]
on WIP

**Comment by alfiyansys** [comment]
> Okay, thank you for your input. I agree with you.
> 
> I believe the `firstIP` parameter is no longer needed since we can obtain it from `firstIp.Mask(cidr.Mask)`. Could you please remove the `firstIp` parameter from both the `GenerateIPListFromCIDR` function and the `GenerateIPListFromCIDRString` function?

firstIp net.IP needed to assign first IP address, from firstIp.Mask(cidr.Mask), while its same as cidr.IP, but results different, not sure why, 

but if using cidr.IP, its looped through 192.x.y.z as class A addresses, not CIDR /21 looped through 192.168.24.x/21.

Maybe problem in inc() function

**Comment by fadhilyori** [comment]
I'm facing a similar issue.

The `cidr.IP` in the `cidr` variable is incremented when `cidr.IP` is utilized.
image


However, if using `ip.Mask(cidr.Mask)` instead, it is normal
image

The problem lies in passing the pointer of `cidr` to the `incr()` function, which causes the IP to be incremented and results in an infinite loop.

I think it is possible to eliminate the `firstIP` parameter in these functions. Instead, we can use `ip.Mask(cidr.Mask)` as a `firstIp`, where the `ip` variable gets from the `net.ParseCIDR()` function.

**Comment by fadhilyori** [comment]
lgtm

**Pull request merged**
